In [1]:
from pathlib import Path
model_ckpt = Path("/rl_benchmark/real_robot/model_checkpoints/XArm_pretrained_ckpt") \

#model_ckpt /= "PlaceCubeInBowlXArm-v5/sac/10-nobbox-eepctl-tz8s4u1p-g90/models/model_1800000.ckpt"
#model_ckpt /= "PlaceCubeInBowlXArm-v7/drq-rgb/10-hcam-eepctl-tongzhou-g90-nohigh-ent0-rs01/models/model_200000.ckpt"
#model_ckpt /= "PlaceCubeInBowlXArm-v7/drq-rgb/0-hcam-rlay-cjit-cfgv2-ent0/models/model_200000.ckpt"
#model_ckpt /= "PlaceCubeInBowlXArm-v7/drq-rgb/10-hcam-rlay-cjit-hue05-randcam-cfgv2-ent0/models/model_100000.ckpt"
#model_ckpt /= "PlaceCubeInBowlXArm-v7/drq-rgb/10-hcam-rlay-cjit-hue05-randcam-cfgv2-ent0/models/model_1800000.ckpt"
#model_ckpt /= "PlaceCubeInBowlXArm-v7/drq-rgb/20-hcam-rlay-cjit-hue05-randcam-cfgv2-ent0/models/model_300000.ckpt"
#model_ckpt /= "PlaceCubeInBowlXArm-v7/drq-rgb/20-hcam-rlay-cjit-hue05-randcam-cfgv2-ent0/models/model_900000.ckpt"
model_ckpt /= "PlaceCubeInBowlXArm-v8/drq-rgb/20-hcam-allimgaug-cfgv2-ent0-noqvel-1hz/models/model_800000.ckpt"

seed = int(str(model_ckpt).split('/')[-3].split('-')[0])
env_name = str(model_ckpt).split('/')[-5]

# cmdline args
args = [
    '/rl_benchmark/pyrl/configs/mfrl/drq/maniskill2/maniskill2_rgbd.py',
    '--eval',
    f"--seed={seed}", "--deterministic", "--gpu-ids", '1',
    "--init-only",  # Only init agent and return
    f"--resume-from={model_ckpt}",

    '--cfg-options',
    f"env_cfg.env_name={env_name}",
    "env_cfg.obs_mode=rgb",
    #"env_cfg.remove_obs_extra=cube_bbox,bowl_bbox",
    "env_cfg.control_mode=pd_ee_delta_pos",
    "env_cfg.horizon=50",
    "env_cfg.image_obs_mode=hand_front",
    "env_cfg.remove_agent_qvel_obs=True"
    
    "rollout_cfg.num_procs=1",
    "agent_cfg.actor_cfg.head_cfg.log_std_clip_tanh=True",
    "agent_cfg.actor_cfg.head_cfg.log_std_bound=-5,2",
    "agent_cfg.gamma=0.9",

    # Turn off wandb logger
    "train_cfg.exp_logger_cfg.type=tensorboard", "train_cfg.exp_logger_cfg._delete_=True",
]

import open3d as o3d
from pyrl.apis.run_rl import main
args, cfg, agent, rollout, evaluator, replay = main(args)

agent = agent.eval()
print("Done")

env_name, seed, model_ckpt

torchsparse is not installed correctly!
No module named 'torchsparse'
Pointnet++ is not compiled
cannot import name 'ball_query_ext' from partially initialized module 'pyrl.utils.cpp_ops.ops_3d.ball_query' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/pyrl/utils/cpp_ops/ops_3d/ball_query/__init__.py)
Piontnet++ is not supported
cannot import name 'PointFPModule' from 'pyrl.networks.modules' (/usr/local/lib/python3.10/dist-packages/pyrl/networks/modules/__init__.py)
SparseConv is not supported
No module named 'torchsparse'


pyrl - (run_rl.py:214) - INFO - 2023-07-17,17:05:28 - Get 1 checkpoint ['/rl_benchmark/real_robot/model_checkpoints/XArm_pretrained_ckpt/PlaceCubeInBowlXArm-v8/drq-rgb/20-hcam-allimgaug-cfgv2-ent0-noqvel-1hz/models/model_800000.ckpt'].
pyrl - (run_rl.py:215) - INFO - 2023-07-17,17:05:28 - Check checkpoint ['/rl_benchmark/real_robot/model_checkpoints/XArm_pretrained_ckpt/PlaceCubeInBowlXArm-v8/drq-rgb/20-hcam-allimgaug-cfgv2-ent0-noqvel-1hz/models/model_800000.ckpt']!
PlaceCubeInBowlXArm-v8-eval - (run_rl.py:433) - INFO - 2023-07-17,17:05:29 - Extra arguments that replace the default setting from the config file.
PlaceCubeInBowlXArm-v8-eval - (run_rl.py:435) - INFO - 2023-07-17,17:05:29 - env_cfg.env_name PlaceCubeInBowlXArm-v8
PlaceCubeInBowlXArm-v8-eval - (run_rl.py:435) - INFO - 2023-07-17,17:05:29 - env_cfg.obs_mode rgb
PlaceCubeInBowlXArm-v8-eval - (run_rl.py:435) - INFO - 2023-07-17,17:05:29 - env_cfg.control_mode pd_ee_delta_pos
PlaceCubeInBowlXArm-v8-eval - (run_rl.py:435) - INF

**Environment type** mani_skill2
SDK_VERSION: 1.11.6
[ENV] No successful init grasp pose found!
[ENV] Contact: actor0.name='link5', actor1.name='link1', sep = -2.044e-02, impulse_norm = 2.877e+01
[ENV] No successful init grasp pose found!


Evaluation-PlaceCubeInBowlXArm-v8-eval - (evaluation.py:108) - INFO - 2023-07-17,17:05:35 - Evaluation environments have seed in [378518883, 378518884)!
PlaceCubeInBowlXArm-v8-eval - (run_rl.py:491) - INFO - 2023-07-17,17:05:35 - Get obs shape!
PlaceCubeInBowlXArm-v8-eval - (run_rl.py:503) - INFO - 2023-07-17,17:05:35 - State shape:{'rgb': [6, 128, 128], 'state': 23}, action shape:4
PlaceCubeInBowlXArm-v8-eval - (run_rl.py:504) - INFO - 2023-07-17,17:05:35 - Environment has the continuous action space with dimension 4.
PlaceCubeInBowlXArm-v8-eval - (run_rl.py:516) - INFO - 2023-07-17,17:05:35 - Final agent config:
{'type': 'DrQ', 'batch_size': 256, 'gamma': 0.9, 'update_coeff': 0.005, 'alpha': 0.2, 'target_update_interval': 1, 'automatic_alpha_tuning': True, 'shared_backbone': True, 'detach_actor_feature': True, 'alpha_optim_cfg': {'type': 'Adam', 'lr': 0.0003}, 'actor_cfg': {'type': 'ContinuousActor', 'head_cfg': {'type': 'TanhGaussianHead', 'log_std_bound': [-5, 2], 'log_std_clip_tan

Done


('PlaceCubeInBowlXArm-v8',
 20,
 PosixPath('/rl_benchmark/real_robot/model_checkpoints/XArm_pretrained_ckpt/PlaceCubeInBowlXArm-v8/drq-rgb/20-hcam-allimgaug-cfgv2-ent0-noqvel-1hz/models/model_800000.ckpt'))

In [2]:
# Test zero qvel after each step
import mani_skill2.envs
import gym
import numpy as np
import torch
from mani_skill2.utils.common import flatten_state_dict
from pyrl.utils.data import GDict

env_sim = gym.make("PlaceCubeInBowlXArm-v8", control_mode="pd_ee_delta_pos",
                   obs_mode="rgb", image_obs_mode="hand_front", remove_agent_qvel_obs=True,
                   control_freq=1)
env_sim._max_episode_steps = 200

obs = env_sim.reset(seed=22)

env_sim.render("human")
env_sim.unwrapped._viewer.toggle_pause(True)

while True:
    env_sim.render("human")

    rgb = []
    for cam_name, cam_obs in obs["image"].items():
        rgb.append(cam_obs["rgb"])
    rgb = np.concatenate(rgb, axis=2)

    obs.pop("image")
    obs["extra"]["tcp_pose"] = obs["extra"]["tcp_pose"].reshape(-1)
    obs.pop("camera_param")
    action = agent(GDict({"rgb": rgb.transpose(2, 0, 1), "state": flatten_state_dict(obs).astype("float32")}).unsqueeze(0, wrapper=False)).cpu().numpy()[0]

    tcp_init_pose = env_sim.tcp.pose  # Checking delta_pose

    obs, reward, done, info = env_sim.step(action)
    print(f"Stepping with action {action}")

    delta_pose = tcp_init_pose.inv() * env_sim.tcp.pose  # Checking delta_pose
    print(f"{delta_pose = } {env_sim.agent.robot.get_qvel()}")
    if done:
        print("Success")
        #break

[2023-07-17 16:55:41.217] [svulkan2] [warning] A second renderer will share the same internal context with the first one. Arguments passed to constructor will be ignored.


[ENV] No successful init grasp pose found!
[ENV] Contact: actor0.name='link5', actor1.name='link1', sep = -2.044e-02, impulse_norm = 2.877e+01
[ENV] No successful init grasp pose found!
Stepping with action [-0.99494 -0.00352  0.95324  0.96756]
delta_pose = Pose([-0.0994282, -0.000350595, 0.09525], [1, -5.58794e-07, -1.40554e-06, 8.70228e-06]) [-0.00001  0.00002 -0.00001 -0.00002  0.00001 -0.00013 -0.00012  0.
 -0.     ]
Stepping with action [-0.98475  0.00596  0.98414  0.98567]
delta_pose = Pose([-0.098769, 0.00661373, 0.0928959], [0.999968, -0.00761089, -0.00214232, -0.00130966]) [ 0.00051  0.00047 -0.00205  0.00081 -0.0044   0.01349 -0.00235  0.01307
 -0.00242]
Stepping with action [ 0.44983  0.21509 -0.00357 -0.90673]
delta_pose = Pose([0.043448, 0.0214861, -0.00114592], [0.999999, -0.000560545, -0.000501616, 0.00100875]) [-0.00004 -0.00007  0.00006 -0.00011  0.00049  0.00006 -0.00019  0.00002
 -0.00079]
Stepping with action [-0.87883 -0.98971 -0.9966  -0.49972]
delta_pose = Pose([

In [1]:
# Simulated env
import mani_skill2.envs
import gym
import numpy as np
import torch
from mani_skill2.utils.common import flatten_state_dict
from pyrl.utils.data import GDict

env_sim = gym.make("PlaceCubeInBowlXArm-v8", control_mode="pd_ee_delta_pos",
                   obs_mode="rgb", image_obs_mode="hand_front", remove_agent_qvel_obs=True,
                   control_freq=1)
env_sim._max_episode_steps = 200

obs = env_sim.reset()
qpos = np.array(
    [0, 0, 0, np.pi / 3, 0, np.pi / 3, -np.pi / 2, 0.0446430, 0.0446430]
)
env_sim.agent.reset(qpos)

tcp_init_pose = env_sim.tcp.pose


SDK_VERSION: 1.11.6
[ENV] No successful init grasp pose found!
[ENV] Contact: actor0.name='link5', actor1.name='link1', sep = -2.044e-02, impulse_norm = 2.877e+01
[ENV] No successful init grasp pose found!


In [2]:
env_sim.unwrapped._sim_freq, env_sim.unwrapped._control_freq, env_sim.unwrapped._sim_steps_per_control

(500, 20, 25)

In [3]:
env_sim.unwrapped._sim_freq, env_sim.unwrapped._control_freq, env_sim.unwrapped._sim_steps_per_control

(500, 1, 500)

In [2]:
env_sim.step_action(np.array([-1, 0, 0, 0]).astype(np.float32))
delta_pose = tcp_init_pose.inv() * env_sim.tcp.pose
delta_pose, env_sim.agent.robot.get_qvel()

(Pose([-0.0999091, 2.44379e-06, -6.73532e-06], [1, -6.13336e-06, -2.2855e-06, 9.20892e-06]),
 array([-7.3464694e-06,  1.4734476e-05, -9.6589501e-06,  2.6022930e-05,
         4.0456625e-06,  2.8937173e-05, -1.0987171e-04, -1.3107644e-05,
        -1.3266461e-05], dtype=float32))

In [2]:
env_sim.step(np.array([-1, 0, 0, 0]).astype(np.float32))
delta_pose = tcp_init_pose.inv() * env_sim.tcp.pose
delta_pose, env_sim.agent.robot.get_qvel()

(Pose([-0.0999091, 2.44379e-06, -6.73532e-06], [1, -6.13336e-06, -2.2855e-06, 9.20892e-06]),
 array([-7.3464694e-06,  1.4734476e-05, -9.6589501e-06,  2.6022930e-05,
         4.0456625e-06,  2.8937173e-05, -1.0987171e-04, -1.3107644e-05,
        -1.3266461e-05], dtype=float32))

In [7]:
env_sim.unwrapped._sim_steps_per_control

25

In [18]:
for _ in range(100):
    env_sim.unwrapped._scene.step()
delta_pose = tcp_init_pose.inv() * env_sim.tcp.pose
delta_pose, env_sim.agent.robot.get_qvel()

(Pose([-0.100118, -0.000308812, 4.53591e-05], [1, 0.000177642, 5.25109e-05, 0.000290275]),
 array([ 8.2710758e-06,  4.0198211e-06, -9.8869205e-06,  2.7021393e-05,
         8.9220703e-07,  2.8985087e-05, -2.8821873e-05, -3.8615544e-06,
        -3.8107391e-06], dtype=float32))

In [2]:
while True:
    env_sim.render("human")